### PR TITLE
Add CMake build script + few fixes of incorrect printf() usage in two files

### PR DESCRIPTION
**Pull request by Wohlstand**
I have added CMake script as an alternative way to compile the project: CMake can be easily used to generate builds for a wide set of toolchains include various versions of MSVC, Xcode, Code::Blocks. CodeLite, Ninja, NMake, GNU/BSD Make, etc. Original makefile and other builds were kept.

The way to build by CMake is:
```
mkdir build
cd build
cmake ..
make -j 4
```

### CODE REVIEW

**Comment by ValleyBell** [comment]
Nice, thanks!

A small request though: Do you think you could fix the printf() commit to not add 500 whitespace-only changes? That would be really nice, because then I could actually see the important changes.

**Comment by Wohlstand** [comment]
> A small request though: Do you think you could fix the printf() commit to not add 500 whitespace-only changes? That would be really nice, because then I could actually see the important changes.

Ok, gonna revert that to show the actual fix of `printf()` usage, anyway, I highly recommending to clean-up line-ending spaces as they are usually garbage, giving any pros and just increasing the size of file...

**Comment by Wohlstand** [comment]
Made just now! Commits are clear now!

**Comment by Wohlstand** [comment]
Anyway, there are next warnings I got:
```
$ ninja
[19/57] Building C object CMakeFiles/opl_23.dir/opl_23.c.o
../opl_23.c: In function ‘CompressVGMData’:
../opl_23.c:443:49: warning: unknown conversion type character ‘!’ in format [-Wformat=]
        printf("Warning! Stereo mismatch at 0x%06!\n", VGMPos);
                                                 ^
../opl_23.c:443:15: warning: too many arguments for format [-Wformat-extra-args]
        printf("Warning! Stereo mismatch at 0x%06!\n", VGMPos);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../opl_23.c:445:49: warning: unknown conversion type character ‘!’ in format [-Wformat=]
        printf("Warning! Stereo mismatch at 0x%06!\n", VGMPos);
                                                 ^
../opl_23.c:445:15: warning: too many arguments for format [-Wformat-extra-args]
        printf("Warning! Stereo mismatch at 0x%06!\n", VGMPos);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../opl_23.c:450:37: warning: unknown conversion type character ‘ ’ in format [-Wformat=]
        printf("Warning! Waveform %02 used at 0x%06!\n", VGMPnt[0x02], VGMPos);
                                     ^
../opl_23.c:450:51: warning: unknown conversion type character ‘!’ in format [-Wformat=]
        printf("Warning! Waveform %02 used at 0x%06!\n", VGMPnt[0x02], VGMPos);
                                                   ^
../opl_23.c:450:15: warning: too many arguments for format [-Wformat-extra-args]
        printf("Warning! Waveform %02 used at 0x%06!\n", VGMPnt[0x02], VGMPos);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[22/57] Building C object CMakeFiles/vgm2txt.dir/chiptext.c.o
../chiptext.c: In function ‘ymf278b_write’:
../chiptext.c:1860:25: warning: format ‘%S’ expects argument of type ‘wchar_t *’, but argument 3 has type ‘char *’ [-Wformat=]
     sprintf(WriteStr, "%S Mix L: 0x%01X = %u%%, 0x%01X = %u%%",
                        ~^
                        %s
       (Register == 0xF9) ? "PCM" : "FM",
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[57/57] Linking C executable vgm_sptd
```

**Comment by ValleyBell** [comment]
Thanks a lot!

**Pull request merged**
